### POST User
POST http://localhost:3000/organizations/{orgId}/users
Content-Type: application/json

{
  "name": "New User",
  "email": "newuser2@example.com"
}

### PUT User
PUT http://localhost:3000/organizations/{orgId}/users
Content-Type: application/json

{
  "userId": "c706c39b-e361-4a12-843d-89ae16c4ec36",
  "name": "Updated user name",
  "email": "updateduser@example.com"
}